package dev.sultanov.workflow;

enum Events {
    INPUT_RECEIVED,
    REQUIREMENTS_EVALUATED,
    REQUIREMENTS_REJECTED,
    SCRIPT_GENERATED,
    SOLUTION_VERIFIED,
    SOLUTION_REJECTED,
    REQUIREMENTS_REWRITTEN,

}
